# Bert baseline for POLAR

## Introduction

In this part of the starter notebook, we will take you through the process of all three Subtasks.

## Subtask 1 - Polarization detection

This is a binary classification to determine whether a post contains polarized content (Polarized or Not Polarized).

In [ ]:
!unzip dev_phase.zip

## Imports

In [3]:
import pandas as pd

from sklearn.metrics import recall_score, precision_score, f1_score
import numpy as np

import torch

from sklearn.metrics import f1_score

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding
)
from torch.utils.data import Dataset

/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
import wandb

# Disable wandb logging for this script
wandb.init(mode="disabled")

## Data Import

The training data consists of a short text and binary labels

The data is structured as a CSV file with the following fields:
- id: a unique identifier for the sample
- text: a sentence or short text
- polarization:  1 text is polarized, 0 text is not polarized

The data is in all three subtask folders the same but only containing the labels for the specific task.

In [5]:
# Load the training and validation data for subtask 1

train = pd.read_csv('../data/dev_phase/subtask1/train/eng.csv')
val = pd.read_csv('../data/dev_phase/subtask1/train/eng.csv')

train.head()

,id,text,polarization
0,eng_973938b90b0ff5d87d35a582f83f5c89,is defending imperialism in the dnd chat,0
1,eng_07dfd4600426caca6e2c5883fcbea9ea,Still playing with this. I am now following Ra...,0
2,eng_f14519ff2302b6cd47712073f13bc461,.senate.gov Theres 3 groups out there Republic...,0
3,eng_e48b7e7542faafa544ac57b64bc80daf,"""ABC MD, David Anderson, said the additional f...",0
4,eng_7c581fb77bce8033aeba3d6dbd6273eb,"""bad people"" I have some conservative values s...",0

In [6]:
train.tail()

,id,text,polarization
3217,eng_d7af338f325fcc12d4c107c591c64a19,the internalized xenophobia seething fr ppl sh...,0
3218,eng_8371147528d6f09acbe9b647c8fa5eb7,the radical left hates chick peas,1
3219,eng_4d188ccdfb84eeeaed31b7f28af538ca,this is how xenophobia and misogyny looks like,1
3220,eng_867cc5be4f80dafae67ab5f0f70a1ee8,yeah and committing war crimes,0
3221,eng_1b3a51105b20c9f022e38a9655fda21e,you are literally siding with Zionists by sayi...,1

# Dataset
-  Create a pytorch class for handling data
-  Wrapping the raw texts and labels into a format that Huggingface’s Trainer can use for training and evaluation

In [7]:
# Fix the dataset class by inheriting from torch.utils.data.Dataset
class PolarizationDataset(torch.utils.data.Dataset):
  def __init__(self,texts,labels,tokenizer,max_length =128):
    self.texts=texts
    self.labels=labels
    self.tokenizer= tokenizer
    self.max_length = max_length # Store max_length

  def __len__(self):
    return len(self.texts)

  def __getitem__(self,idx):
    text=self.texts[idx]
    label=self.labels[idx]
    encoding=self.tokenizer(text,truncation=True,padding=False,max_length=self.max_length,return_tensors='pt')

    # Ensure consistent tensor conversion for all items
    item = {key: encoding[key].squeeze() for key in encoding.keys()}
    item['labels'] = torch.tensor(label, dtype=torch.long)
    return item

Now, we'll tokenize the text data and create the datasets using `bert-base-uncased` as the tokenizer.

In [8]:
# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

# Create datasets
train_dataset = PolarizationDataset(train['text'].tolist(), train['polarization'].tolist(), tokenizer)
val_dataset = PolarizationDataset(val['text'].tolist(), val['polarization'].tolist(), tokenizer)

Next, we'll load the pre-trained `bert-base-uncased` model for sequence classification. Since this is a binary classification task (Polarized/Not Polarized), we set `num_labels=2`.

In [9]:
train_dataset.texts

[' is defending imperialism in the dnd chat',
 'Still playing with this. I am now following Rachel Maddie from msnbc.',
 '.senate.gov Theres 3 groups out there Republicans, Democrats and the People. If the Democrats have little power, organize the People.',
 '"ABC MD, David Anderson, said the additional funds would provide improved financial certainty stability. "Continued investment in ABC is critical to support the democratic process, reflect our unique culture build our national identity thru Australian stories." More "Peter Dutton says"?',
 '"bad people" I have some conservative values so does that make me one of those Paul? Honest question.',
 '"Enemy of the people" was a phrase coined and used during the Stalinist show trials in the Soviet Union. It has no place in a democratic society',
 '"He also voiced support for Elon Musk, Tommy Robinson and Alternative for Germany, the farright antiimmigration party." Yeah, complete mystery.',
 '"If you disagree with imperialism, youre a supporter of imperialism"',
 '"italian" as a national identity is totally oversold in meme culture. its a relaitvely new concept, they even speak different languagesdialects, the italian language is a modern made up construct. even pizza isnt the same in all of italy, we always think napoli style but thats only one',
 '"No to ethnic cleansing". QudsDay QudsMainIssue',
 '"Remember that the frontier of the rebellion is EVERYWHERE and even the smallest act of insurrection pushes our lines forward." Karis Nemik, Andor',
 '"Saved Ukraine FOR NATO expansion" you mean. Right?',
 '"Talks to reach a Gaza ceasefire and hostage release deal between Israel and Hamas are 90 complete, but key issues remain that need to be bridged, a senior Palestinian official involved in the talks told the BBC." worldrss.bsky.social @URL',
 '"This is another argument, if any were needed, for even stricter sanctions on the Russian economy and even more support for Ukraine in resisting Russian aggression." .bsky.social wapo.st3ZTLs95',
 '"Well said. Multiculturalism enriches societies, and figures like Farage thrive on fear and misinformation. Heres to calling out divisiveness and celebrating diversity instead."',
 '1 million Ukrainian refugees would be 7.3 million US refugees adjusting for population',
 '1 of 3 Republicans on Stamford 40member Board of Reps',
 '100 of Palestinians in Gaza and 95 of Palestinians in the West Bank live under Palestinian law.',
 '100 Years Later, Zeev Jabotinskys Hawkish Zionism',
 '12 Source CNN Source CNN Business Source CNN Business Source CNN Business Source CNN Business',
 '15 candidates file for spot on GOP primary ballot in MarchThe Lufkin Daily',
 '17 political cartoons tackle Donald Trumps',
 '1SS There would be no Gaza and the West Bank.',
 '2 IOF soldiers were wounded after Palestinians threw an IED at their Jeep in the West Bank',
 '2020 elections by the swing states, Big Tech, CNN, MSNBC, CBS, Wikipedia, YouTube. And part 2 will be on midterms.',
 '25 OF Ukraine territory and 80 of Ukraine wealthproducing sector is that enough? And for a bonus denazification!!!',
 '3 Ohio Republicans accuse shared campaign treasurer',
 '4 Dems, 2 Republicans Luzerne County Council seatsTimes Leader',
 '47th District Republicans kicked out of Kent Cornucopia',
 '5 takeaways on Republicans first impeachment hearing',
 '91. Salaar Part 1 Ceasefire 2023.',
 'A chorus of Democrats was asked to sing the praises',
 'A CNN journalist pronounced DOGE douche',
 'A Disturbing Amount of Democrats, Young People Want',
 'A federal election fraud felony conviction!',
 'A look at day one of Texas AG Ken Paxtons impeachment',
 'A loss of humanity in discussing Hamas',
 'A Marketing company out of San Diego is currently hiring freelance writers to come up with the next online conspiracy theory. This is the world we live in. @URL',
 'A Salute to Service: Christian County Honors Veterans',
 'A story of genocide, colonization, greed and deforestationThe Circle',
 'A TV News Reporter on IsraelHamas Fog of War, Truth',
 'A victory for voting rights in Wisconsin! Yesterday, the Wisconsin Supreme Court decided to preserve the ability of cities to designate inperson absentee voting sites and to use a mobile voting van. StateCourtsMatter @URL',
 'A week ago Ukraine invasion was fear mongering too',
 'A Week of Good and Bad News for Joe BidenThe New Yorker',
 'A West Bank Pizza Restaurant Mocked Holocaust Survivor',
 'A West Bank Pizza Restaurant Mocked Holocaust Survivor Taken',
 'A.S. Senate passes bill condemning Hamas',
 'Absolutely no evidence of voter fraud Democrats',
 'Abuse survivor recounts her struggles at YWCA',
 'ACNUR Costa Rica Factsheet Diciembre 2024 Refugees',
 'Activists call for Rep. Caraveos of immigration',
 'Add Breitbart, OAN, and Newsmax to that list.',
 'Admission to election interference it seems.',
 'Advance voting begins in Ontario today. You dont need your voter registrationinformation card to vote, just ID with your name and address. Lets gooooo',
 'Advice for Vegans by a Vegan',
 'Africas Economics and Its Take On the IsraeliPalestinian',
 'After election defeats, Butler County GOP leader pleads',
 'After Georgia indictments, Young tells Republicans to not',
 'After Hamas assault, Israel attacking innocent Palestinians',
 'After hostage killings, can IsraelHamas ceasefire talks be revived?',
 'After Mayotte, Cyclone Chido hits Mozambique Refugees',
 'After navigating immigration system, JaeRam Lee of Grand',
 'After recount, writein Liam Watson wins Blacksburg Town',
 'Again, Israel is NOT the Jewish state. It is the ISRAELI state. It is the state for all Israelis, Jew, Palestinian, Arab, Druze, whatever.',
 'Age is a sore spot for Joe Biden. Heres why Bernie',
 'Agreed. I refuse to watch Jennings on CNN.',
 'Ahh gotcha, I thought you meant during early voting.',
 'Albanians are neither refugees or asylum seekers',
 'All across America, the success of Bidenomics is well',
 "All in the Family: Sheriff's Son Is New DPS Officer",
 'All the spoilers are on Fox News daily.',
 'Also Kamala Harris speech on the same subject?',
 'America First Republicans appear in court as infighting',
 'American Legion 102 Presents Service Awards',
 'American legislation sanctions cotton and goods produced in Xinjiang and American legislation sanctions procurement boycotts of Israel',
 'Amid ceasefire push, Palestinians released from Israeli jails bear mental, physical scars @URL',
 'Amid Challenges, Israeli Basketball Team Plays with a',
 'Amid the Ukraine war, are sanctions against Russia working?',
 'anchors know Donald Trump lost the',
 'and a hangar with US military aid paid for by US taxpayers',
 'And as far as your gun control, Chicago knows gun control..',
 'and everywhere else they can which is all swing states',
 'And how about the electoral college bill?',
 'And refused to allow DOJ election monitors into polling places!',
 'And that has what to do with russian aggression in Ukraine today',
 'and they wonder why people dont like "asylum seekers"',
 'And this is where the radical left and radical right meet.',
 'and what do the asylum seekers say?',
 'And yet you want the US to send military aid to Ukraine. Did you actually read what you just wrote?',
 'Andrews Ice Block about Ice Blocks',
 'Angel Island exhibit explores disenfranchisement of Chinese',
 'Ann Arbor community members protest in of Israeli',
 'Annelle Sheline Jordan braces as Israeli annexation of West Bank looms responsiblestatecraft.orgisraelannex...',
 'Another 3 billion in military aid for Ukraine.',
 'AntiSemitic Hawaii Peace Activists tied to Hamas, Iran',
 'Antisemitic propaganda group Goyem TV relocates',
 'Antony Blinken gets it exactly right in case against HamasThe Iola',
 'Any anti second amendment Ukrainians out there?',
 'Any reason why LEGAL immigration isnt what were fighting for?',
 'anyway, he just leaked it to Breitbart unless you think the FBI would choose Breitbart to leak to',
 'AOC and Kamala Harris dont really care.',
 'AOC slams GOP for criticizing Bowman over fire alarm',
 'Appalling decision by Robert Fico to visit Putin. Europe must stand united against Russian aggression, not suck up to authoritarians. @URL',
 'Appeals court rules for Evergreen teacher who wore MAGA',
 'are we still pretending NATO expansion is not part of the balanced take on the situation?',
 'Are you suggesting by disallowing humour andor crisps we will solve the middle east crisis?',
 'Arizona Republicans formally oppose new Grand Canyon',
 'Arizonans in Israel bear witness to Israelis scariest time',
 'Armstrong voter registration tables leaves students satisfiedThe GeorgeAnne',
 'Arrest staff Leonardo for election fraud',
 'Arresting Donald Trump Could Be Great for DWAC',
 'Articles of impeachment. Thats what you need to do.',
 'Artsakh refugees not granted Armenian citizenship',
 'As IDF advances in Gaza, Hamas chief Haniyeh claims',
 'As Israel ends 2day West Bank offensive, Palestinian',
 'As Maryland GOP seeks to rebuild, former leaders feel',
 'As well as in unvaccinated Red states.',
 'Ashland Boy Bonds with Long-Awaited Service Dog',
 'ASU Jewish Studies gives context to IsraeliPalestinian',
 'Asylum seekers can work 6 months after they apply for asylum.',
 'At 1030pm, Eastern time, I could no longer scroll TikTok. Time to go scroll on RedNote like the naughty little socialist I am.',
 'At Sunday Vigil, More Than 1000 Mourn Victims of Hamas',
 'At synod prayer service, pope calls for immigration reform',
 'Attorney Gurfinkel Answers Immigration Questions from Community',
 'Atty. Gurfinkel answers more immigration questions',
 'Azerbaijani Flights to Israeli Arms Export Base Spike',
 'Baltimore Parents Grapple With Children Serving in the IDFBaltimore Jewish',
 'Baltimore Police Commissioner Harrison to Leave Contract Early',
 'BankTurn Out for FIDF ShabbatAtlanta Jewish',
 'Bargain Airline to Begin Commercial Service Out of Salem',
 'Based Ryukishi acknowledging Japans war crimes',
 'Bay Area Israelis and Palestinians watch developing war',
 'Because Russia has s400 and will shoot them down. UA needs missile defense like Iron Dome.',
 'Because the west isnt going to send military aid, which is what they really want.',
 'Belleville City Council Approves Kris Faull as Police Chief',
 'Bellwether elections spell victory for Democrats, LGBTQ',
 'Benson Says Clerks Statewide Are Ready for Early Voting',
 'Benson says clerks statewide are ready for early voting',
 'Berkeley elected officials sign letter for ceasefire in Gaza',
 'Bernardsville Democrats back business improvement districtNew Jersey Hills Media Group',
 'Biden administration, CISA face new limits in GOP First',
 'Biden announces nearly US2.5B in military aid for Ukraine',
 'Biden condemns Hamas, Putin asks Congress for 100',
 'Biden got Mexico to invest in 1.5 billion for border security. What did trump get?',
 'Biden hits Russia with sanctions, shifts troops',
 'Biden impeachment inquiry revs up after House GOPs',
 'Biden Kamala Harris what you think.',
 'Biden says body of IsraeliAmerican hostage among six',
 'Biden says no ceasefire in IsraelHamas war until hostages',
 'Biggest mistake of my life Regret sets in for Trump voters as Republican politicians panic MSNBC',
 'Bill Cassidy says Donald Trump should exit presidential',
 'BISF hosts panel on longstanding IsraeliPalestinian conflictThe Rice Thresher',
 'Black America Divided Over Hamas Attack on Israel',
 'Blessed days, please help the children of besieged Gaza',
 'Blog Published May 3, 2023 2 minute read Republican Efforts to Defund Border Security',
 'Bloop "No thanks White South Africans turn down Trumps immigration offer" @URL',
 'Blue States are building back better than red states',
 'Blue states are flailing. Bring it.',
 'BMS Student Recognized by Decatur Police Department',
 'Boebert touts work to GOP voters in SW Colorado',
 'Boebert touts work to GOP voters in SW Colorado, but theater',
 'Boeberts Antics Could Cost GOP a House Seat',
 'Bonneville County GOP discusses tectonic rule',
 'Bonutti Technologies Develops Device to Disinfect Surfaces',
 'Bossier Senate race shreds alliances as Republicans',
 'Boulder County GOP refuses to certify 2023',
 'Brandeis professor mourns family killed in Israel by Hamas',
 'Brandeis suspends class to hold teachins on IsraelHamas',
 'BREAKING Antigua Barbuda and Armenia reach agreement for 58day ceasefire.',
 'BREAKING Panama and Lesotho reach agreement for 68year ceasefire.',
 'BREAKING US sources Joe Biden will visit Israel, the West Bank, and Saudi Arabia in a tour that will continue from July 13 to 16',
 'Britain announced a new package of military aid to Ukraine worth 286 million, Reuters. Thank you, Britain',
 'Bryan Smith elected as Idaho GOP',
 'Bucks County native Carol Simantoc killed in Hamas',
 'But Democrats would never do the same thing back to the red states. They know that.',
 'by Alexis de Tocqueville. Strong institutions. And common stories that forge a unified national identity. All three are being eroded.',
 'California Democrats say Kamala Harris could have upper',
 'California Police Department to Take Back Unwanted Medications',
 'Californias Republicans should break from Donald',
 'Calls for action by exHamas leader put LAPD, sheriffs',
 'Can anyone beat Donald Trump in Iowa? 40',
 'Can Haley beat Trump in SC GOP primary? What polls tell',
 'Can Nikki Haley break Donald Trumps grip in NH ahead',
 'Can they tack on the electoral college too',
 'Can we throw out the electoral college, NOW? ONEPERSONONEVOTE',
 'Can you imagine the media frenzy if President Joe Biden had forgotten to swear someone in?',
 'Canadas Border Security Agency is seeking interest in highly qualified workers possibly displaced by a sudden change in US policy on immigration. Experience with circumvention of border security measures an asset. Be advised pay will be in Pesos due to resent decline in our National Currency.',
 'Cant be a ceasefire with Russian soldiers in Ukraine',
 'capitalism really popped off with christmas',
 'Car slams into parked SUV protecting Joe Bidens',
 'CBS News U.S. has intel that Russian commanders have orders to proceed with Ukraine invasion',
 'Ceasefire and complete withdrawal would be in line with Ukraines position.',
 'Ceasefire is not in Putin vocabulary.',
 'CeaseFire Israel release the children Palestine',
 'Change your voter registration to no partyindependent. @URL',
 'Charlottesville, Albemarle Democrats declare victory over',
 'China warns US to stop arming Taiwan after Biden approves 571M in military aid Highlights President Biden authorized an additional 571 million in funding to Taiwan for military aid.... GeneralNews Source Fox News What do you think?',
 'Chipley Garden Club Installs New Officers',
 'City Council continues to hear calls for ceasefire in GazaThe Michigan',
 'City of Chickasha Hires Assistant Police Chief',
 'Claim that Rep. Van Orden was at Jan. 6 insurrection',
 'College Democrats and College Republicans debate',
 'College of Letters and Sciences hosts panel recounting',
 'Colorado case seeking to disqualify Donald Trump',
 'Colorado courts Donald Trump ruling sets off political',
 'Colorado Republicans praise, Democrats slam U.S. House',
 'Colorado Supreme Court ruling in Donald Trump ballot',
 'Colorado voters sue to disqualify Donald Trump',
 'Community West Bank agrees to 100M',
 'Concerning Bidenomics and the new House',
 'Conrads continue to mourn loss of son',
 'Conservative news site Illinois Review critical of GOP',
 'Considering how much the riots cost the UK, maybe he and his mates should stop spreading disinformation about asylum seekers and provoking hatred.',
 'Constitutionally theyre not allowed to during a state of war. How can you open polling places if theyll just be targets for bombing, how do you get the diaspora, occupied territories and refugees to have their voices heard? How do you account for foreign meddling and cries of illegitimacy?',
 'Contested races across county early voting',
 'continued military aid to Ukraine, and controversial climate initiatives." "As Congress spends to reward its favored pet projects, the American taxpayers are forced to pay through high prices and crippling interest rates," Paul said.',
 'Cop Talk Featuring Bay City Police Detective Chris Scheduled',
 'Cornell Students Call on University to Divest from Israeli',
 'Correction... blue cities in red states',
 'Couldnt electoral colleges upend the results and vote Kamala Harris in?',
 'County GOP committee ousts antiTrump memberNewsPress NOW',
 'County Voices Concerns Over Randolph Hospital Situation',
 'Crean fake news sobre muerte de Jennifer',
 'CSG holds meeting, students speak on IsraelHamas warThe Michigan',
 'Culver City Appoints New Mayor and Vice Mayor in Historic Move',
 'CWRU community walks out on universitys IsraelHamas war',
 'Dalton Man Accused of Firing at Police',
 'Danbury Democrats flip City Council, take supermajority',
 'Danbury Democrats landslide victory flips balance',
 'David Emanuel Academy Thanks Stillmore Police Department',
 'Dean Plocher officially joins GOP primary for Missouri',
 'Dear Allah, please protect all Muslim in Gaza',
 'Dearborn Police Commander Updates Council on Operations',
 'Death of Manuel Ellis sparked police reform in Tacoma',
 'Death toll in stifling Texas prisons climbs, Democrats seek',
 'Deepfake news videos ramp up misinformation',
 'Defense Department announces 275 million military aid to Ukraine',
 'Defund the police. Fund the Sheriffs.',
 'Dem bill would hold West Bank settlers accountable for violence Doubt it',
 'Dem bill would hold West Bank settlers accountable for violence. newsletters.mondoweiss.nettlcleyJ2Ij...',
 'Democrats accuse Twitter of profiting off Hamas',
 'Democrats Bardi and Biront vow to grow Roselands sense',
 'Democrats Choose Suozzi for Special ElectionIrish Echo',
 'Democrats Denounce Right-Wing News Pipeline Used in Campaigns',
 'Democrats discuss insurance, schools in state House',
 'Democrats finally seem ready to wage war on Fox',
 'Democrats flip red, Republicans flip blue on Ukraine. Is it',
 'Democrats Kill Bill to Legalize Alcohol in Strip ClubsThe Stranger',
 'Democrats lose on Long Island, make gains elsewhereThe Hofstra',
 'Democrats meet for dinner ahead of municipal electionsMadison Courier',
 'Democrats plan to nominate Biden by virtual',
 'Democrats push for 17 minimum wage by 2028The Charlotte',
 'Democrats running in Oyster Bay raise ethics issues',
 'Democrats scrambling to find alternatives to scandal',
 'Democrats sweep Ogdensburg city council seats, Tooley',
 'Democrats take control of Chesterfield County',
 'Demonstrators march in for ceasefire in Gaza',
 'Dems stuck with Biden, GOP has momentum',
 'Denazification and demilitarisation is Russias Get Brexit Done',
 'DeSantis has pledges to deploy Florida National Guard to assist with Kari Lakes planned border security mission',
 'DFA leaves IDFA, showing split over',
 'DFL bill would create automatic voter registration, restore',
 'Did Donald Trump Steal His Act from Brother Theodore?The Village Voice',
 'Did Kamala Harris run this strategy?',
 'Did not have agreeing with Mike Pence and Steve Bannon on my 2025 Bingo card.',
 'Did they have early voting in Alabama?',
 'Didnt even realise we had Border security.',
 'Didnt they get their military aid still. Eep. This goes back further than 45 or even Bill Clinton.',
 'Didnt you request for his deportation ?',
 'Distracted Joe Biden is not good',
 'DIY border fix? Texas tests limits on immigration policy.The Christian Science Monitor',
 'Do you think these price increases are a result of the RussiaUkraine war yet? I dont think so.',
 'Do you want to sue Joe Biden? Kansas AG Kris Kobach',
 'Does New Zealand have a Second Amendment?',
 'does sjw stand for social justiceshipping warrior',
 'Doesnt she believe in open borders?',

In [10]:
# Load the model
model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2293.80it/s, Materializing param=bert.pooler.dense.weight]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Now, we'll define the training arguments and the evaluation metric. We'll use macro F1 score for evaluation.

In [11]:
# Define metrics function
def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    return {'f1_macro': f1_score(p.label_ids, preds, average='macro')}

# Define training arguments
training_args = TrainingArguments(
        output_dir=f"./",
        num_train_epochs=3,
        learning_rate=2e-5,
        per_device_train_batch_size=64,
        per_device_eval_batch_size=8,
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=100,
        disable_tqdm=False
    )

Finally, we'll initialize the `Trainer` and start training.

In [12]:
# Initialize the Trainer
trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=val_dataset,            # evaluation dataset
    compute_metrics=compute_metrics,     # the callback that computes metrics of interest
    data_collator=DataCollatorWithPadding(tokenizer) # Data collator for dynamic padding
)

# Train the model
trainer.train()

# Evaluate the model on the validation set
eval_results = trainer.evaluate()
print(f"Macro F1 score on validation set: {eval_results['eval_f1_macro']}")

/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Macro F1 score on validation set: 0.8706613851700615

# Subtask 2: Polarization Type Classification
Multi-label classification to identify the target of polarization as one of the following categories: Gender/Sexual, Political, Religious, Racial/Ethnic, or Other.
For this task we will load the data for subtask 2.

In [13]:
train = pd.read_csv('../data/dev_phase/subtask2/train/eng.csv')
val = pd.read_csv('../data/dev_phase/subtask2/train/eng.csv')
train.head()

,id,text,political,racial/ethnic,religious,gender/sexual,other
0,eng_973938b90b0ff5d87d35a582f83f5c89,is defending imperialism in the dnd chat,0,0,0,0,0
1,eng_07dfd4600426caca6e2c5883fcbea9ea,Still playing with this. I am now following Ra...,0,0,0,0,0
2,eng_f14519ff2302b6cd47712073f13bc461,.senate.gov Theres 3 groups out there Republic...,0,0,0,0,0
3,eng_e48b7e7542faafa544ac57b64bc80daf,"""ABC MD, David Anderson, said the additional f...",0,0,0,0,0
4,eng_7c581fb77bce8033aeba3d6dbd6273eb,"""bad people"" I have some conservative values s...",0,0,0,0,0

In [14]:
# Fix the dataset class by inheriting from torch.utils.data.Dataset
class PolarizationDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length # Store max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(text, truncation=True, padding=False, max_length=self.max_length, return_tensors='pt')

        # Ensure consistent tensor conversion for all items
        item = {key: encoding[key].squeeze() for key in encoding.keys()}
        # CHANGE THIS LINE: Use torch.float instead of torch.long for multi-label classification
        item['labels'] = torch.tensor(label, dtype=torch.float)
        return item

In [15]:
# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

# Create train and Test dataset for multilabel
train_dataset = PolarizationDataset(train['text'].tolist(), train[['gender/sexual','political','religious','racial/ethnic','other']].values.tolist(), tokenizer)
val_dataset = PolarizationDataset(val['text'].tolist(), val[['gender/sexual','political','religious','racial/ethnic','other']].values.tolist(), tokenizer)
dev_dataset = PolarizationDataset(val['text'].tolist(), val[['gender/sexual','political','religious','racial/ethnic','other']].values.tolist(), tokenizer)

In [16]:
# Load the model
model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=5, problem_type="multi_label_classification") # 5 labels

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2256.24it/s, Materializing param=bert.pooler.dense.weight]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [17]:
# Define metrics function for multi-label classification
def compute_metrics_multilabel(p):
    # Sigmoid the predictions to get probabilities
    probs = torch.sigmoid(torch.from_numpy(p.predictions))
    # Convert probabilities to predicted labels (0 or 1)
    preds = (probs > 0.5).int().numpy()
    # Compute macro F1 score
    return {'f1_macro': f1_score(p.label_ids, preds, average='macro')}

# Define training arguments
training_args = TrainingArguments(
    output_dir=f"./",
    num_train_epochs=3,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=100,
    disable_tqdm=False
)

In [18]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics_multilabel,  # Use the new metrics function
    data_collator=DataCollatorWithPadding(tokenizer)
)

# Train the model
trainer.train()

# Evaluate the model on the validation set
eval_results = trainer.evaluate()
print(f"Macro F1 score on validation set for Subtask 2: {eval_results['eval_f1_macro']}")

/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Macro F1 score on validation set for Subtask 2: 0.4526790405303978

# Subtask 3: Manifestation Identification
Multi-label classification to classify how polarization is expressed, with multiple possible labels including Vilification, Extreme Language, Stereotype, Invalidation, Lack of Empathy, and Dehumanization.

In [19]:
train = pd.read_csv('../data/dev_phase/subtask3/train/eng.csv')
val = pd.read_csv('../data/dev_phase/subtask3/train/eng.csv')

train.head()

,id,text,stereotype,vilification,dehumanization,extreme_language,lack_of_empathy,invalidation
0,eng_973938b90b0ff5d87d35a582f83f5c89,is defending imperialism in the dnd chat,0,0,0,0,0,0
1,eng_07dfd4600426caca6e2c5883fcbea9ea,Still playing with this. I am now following Ra...,0,0,0,0,0,0
2,eng_f14519ff2302b6cd47712073f13bc461,.senate.gov Theres 3 groups out there Republic...,0,0,0,0,0,0
3,eng_e48b7e7542faafa544ac57b64bc80daf,"""ABC MD, David Anderson, said the additional f...",0,0,0,0,0,0
4,eng_7c581fb77bce8033aeba3d6dbd6273eb,"""bad people"" I have some conservative values s...",0,0,0,0,0,0

In [20]:
# Fix the dataset class by inheriting from torch.utils.data.Dataset
class PolarizationDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length # Store max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(text, truncation=True, padding=False, max_length=self.max_length, return_tensors='pt')

        # Ensure consistent tensor conversion for all items
        item = {key: encoding[key].squeeze() for key in encoding.keys()}
        # CHANGE THIS LINE: Use torch.float instead of torch.long for multi-label classification
        item['labels'] = torch.tensor(label, dtype=torch.float)
        return item

In [21]:
# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

# Create train and Test dataset for multilabel
train_dataset = PolarizationDataset(train['text'].tolist(), train[['vilification','extreme_language','stereotype','invalidation','lack_of_empathy','dehumanization']].values.tolist(), tokenizer)
val_dataset = PolarizationDataset(val['text'].tolist(), val[['vilification','extreme_language','stereotype','invalidation','lack_of_empathy','dehumanization']].values.tolist(), tokenizer)

In [22]:
# Load the model
model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=6, problem_type="multi_label_classification") # use 6 labels

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2110.11it/s, Materializing param=bert.pooler.dense.weight]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [23]:
# Define training arguments
training_args = TrainingArguments(
    output_dir=f"./",
    num_train_epochs=3,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=100,
    disable_tqdm=False
)

# Define metrics function for multi-label classification
def compute_metrics_multilabel(p):
    # Sigmoid the predictions to get probabilities
    probs = torch.sigmoid(torch.from_numpy(p.predictions))
    # Convert probabilities to predicted labels (0 or 1)
    preds = (probs > 0.5).int().numpy()
    # Compute macro F1 score
    return {'f1_macro': f1_score(p.label_ids, preds, average='macro')}

In [24]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics_multilabel,  # Use the new metrics function
    data_collator=DataCollatorWithPadding(tokenizer)
)

# Train the model
trainer.train()

# Evaluate the model on the validation set
eval_results = trainer.evaluate()
print(f"Macro F1 score on validation set for Subtask 3: {eval_results['eval_f1_macro']}")

/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
/Users/davorangelov/VscodeProjects/semeval-polar-project/venv/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Macro F1 score on validation set for Subtask 3: 0.5360886896470324